version: "2.3"

services:
  inf3995-vue-app:
    image: dockerize-inf3995-vuejs-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inf3995-vue-app
    volumes:
      - ./:/app
      - /app/node_modules
    network_mode: host
    