image: mcr.microsoft.com/vscode/devcontainers/python:3.8

variables:
  WORKING_DIRECTORY: "backend"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

workflow:
  rules:
    - changes:
        - $WORKING_DIRECTORY/**/*

stages:
  - install_dependencies
  - lint
  - test

.cache_template: &cache_configuration  # Hidden yaml configuration that defines an anchor named 'cache_configuration'
  cache: 
    key: $CI_COMMIT_REF_SLUG-$WORKING_DIRECTORY
    paths:
      - $PIP_CACHE_DIR
    policy: pull

prepare:
  stage: .pre
  script:
    - cd $WORKING_DIRECTORY
    - pip install -r requirements.txt
  cache:
    key: $CI_COMMIT_REF_SLUG-$WORKING_DIRECTORY
    paths:
      - $WORKING_DIRECTORY/node_modules/

install_dependencies:
  stage: install_dependencies
  cache:
    key: $CI_COMMIT_REF_SLUG-$WORKING_DIRECTORY
    paths:
      - $WORKING_DIRECTORY/node_modules/
  script:
    - cd $WORKING_DIRECTORY
    - pip install -r requirements.txt
  only:
    changes:
      - $WORKING_DIRECTORY/requirements.txt
      - $WORKING_DIRECTORY/Dockerfile
      - $WORKING_DIRECTORY/.devcontainer/Dockerfile

lint_backend:
  stage: lint
  <<: *cache_configuration            # Merge the contents of the 'cache_configuration' alias
  script:
    - cd $WORKING_DIRECTORY
    - find . -type f -name '*.py' | xargs pylint  --rcfile pylintrc

test_backend:
  stage: test
  <<: *cache_configuration            # Merge the contents of the 'cache_configuration' alias
  script:
    - cd $WORKING_DIRECTORY
    - pytest
